### ISSUE TITLE
bug: @fcanvas/communicate type definition has issues

### ISSUE THREAD

**Issue by rxliuli** [tachibana-shin/fcanvas-next#11]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

When using put/listen, I discovered there were issues with type inference, as shown in the image

<img width="389" alt="image" src="https://github.com/user-attachments/assets/a5c4dc17-1ccd-43d2-88a6-81f154c5f121">

```ts
test("should correctly infer return type for put function", async () => {
  const r = await put<{
    add(a: number, b: number): number
    toString(num: number): string
  }>(self, "add", 1, 2)
  expect<number>(r) // string | number' is not assignable to parameter of type 'number'
})
```

But I don't know how to solve this TypeScript issue, I just wrapped it simply in my own project to resolve it. Would you be willing to accept a PR?

```ts
export function defineMessaging<
  T extends Record<string, (...args: any[]) => any>,
>(): Messaging<T> {
  return {
    onMessage(port, name, cb) {
      listen(port, name as any, cb)
    },
    sendMessage(port, name, ...args) {
      return put(port, name, ...args)
    },
  }
}

const { sendMessage } = defineMessaging<{
  add(a: number, b: number): number
  toString(num: number): string
}>()
expect<number>(await sendMessage(self, 'add', 1, 2)) // Working
expect<string>(await sendMessage(self, 'toString', 1)) // Working
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by tachibana-shin** [comment]
Yeah! I always welcome PRs.

**Comment by tachibana-shin** [comment]
I remembered this you can try
```typescript
 await put<{
    add(a: number, b: number): number
    toString(num: number): string
  }, "add">(self, "add", 1, 2)
```

**Comment by tachibana-shin** [comment]
This is due to some limitations of typescript, I will add a new more concise api in the new version it will look like
```typescript
put<{
  add(a: number, b: number): number
  toString(num: number): string
}>(self)("add", 1, 2)
```

**Comment by rxliuli** [comment]
Have you considered supporting callbacks, like what comlink does?

<img width="854" alt="image" src="https://github.com/user-attachments/assets/38e340e8-b530-4300-a5f8-5826f2bdab1f">

**Comment by tachibana-shin** [comment]
> Have you considered supporting callbacks, like what comlink does?
> 
> <img alt="image" width="854" src="https://private-user-images.githubusercontent.com/24560368/373149029-38e340e8-b530-4300-a5f8-5826f2bdab1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDI3OTUsIm5iZiI6MTcyNzk0MjQ5NSwicGF0aCI6Ii8yNDU2MDM2OC8zNzMxNDkwMjktMzhlMzQwZTgtYjUzMC00MzAwLWE1ZjgtNTgyNmYyYmRhYjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA4MDEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3Y2IyZDFhNDBhMzkwZjk5YmNiNGQ4YjFlNWRhMTk5NGYyM2JhYTlmMDllNDc4ZDc3YWJjZWVmZDljM2VhNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wq9a_3m7yeOSp0OhzSXbVuCgFFHYZXw4VfFndn6ApbY">

I have no intention of adding it to this library. The callback function is already supported by me in my `workercom` library: https://npmjs.org/package/workercom
